name: python-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - jupyterlab
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - altair
  - vega
  - vega_datasets
  - opentsne
  - umap-learn